[2023-11-05T01:57:09.248+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: spark_airflow_dag.spark_submit_task manual__2023-11-05T01:56:54.458640+00:00 [queued]>
[2023-11-05T01:57:09.265+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: spark_airflow_dag.spark_submit_task manual__2023-11-05T01:56:54.458640+00:00 [queued]>
[2023-11-05T01:57:09.266+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2023-11-05T01:57:09.286+0000] {taskinstance.py:1380} INFO - Executing <Task(SparkSubmitOperator): spark_submit_task> on 2023-11-05 01:56:54.458640+00:00
[2023-11-05T01:57:09.295+0000] {standard_task_runner.py:57} INFO - Started process 293 to run task
[2023-11-05T01:57:09.340+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'spark_airflow_dag', 'spark_submit_task', 'manual__2023-11-05T01:56:54.458640+00:00', '--job-id', '2', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmp2u2f5453']
[2023-11-05T01:57:09.366+0000] {standard_task_runner.py:85} INFO - Job 2: Subtask spark_submit_task
[2023-11-05T01:57:09.511+0000] {logging_mixin.py:151} WARNING - /home/airflow/.local/lib/python3.9/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2023-11-05T01:57:09.652+0000] {task_command.py:415} INFO - Running <TaskInstance: spark_airflow_dag.spark_submit_task manual__2023-11-05T01:56:54.458640+00:00 [running]> on host dataeng-airflow-scheduler
[2023-11-05T01:57:09.815+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='dibimbing' AIRFLOW_CTX_DAG_ID='spark_airflow_dag' AIRFLOW_CTX_TASK_ID='spark_submit_task' AIRFLOW_CTX_EXECUTION_DATE='2023-11-05T01:56:54.458640+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-11-05T01:56:54.458640+00:00'
[2023-11-05T01:57:09.889+0000] {base.py:73} INFO - Using connection ID 'spark_tgs' for task execution.
[2023-11-05T01:57:09.891+0000] {spark_submit.py:340} INFO - Spark-Submit cmd: spark-submit --master spark://dataeng-spark-master:7077 --name arrow-spark /spark-scripts/transform.py
[2023-11-05T01:57:39.234+0000] {spark_submit.py:491} INFO - Traceback (most recent call last):
[2023-11-05T01:57:39.237+0000] {spark_submit.py:491} INFO - File "/spark-scripts/transform.py", line 10, in <module>
[2023-11-05T01:57:39.239+0000] {spark_submit.py:491} INFO - load_dotedev(dotedev_path=dotedev_path)
[2023-11-05T01:57:39.239+0000] {spark_submit.py:491} INFO - NameError: name 'load_dotedev' is not defined
[2023-11-05T01:57:39.309+0000] {spark_submit.py:491} INFO - 23/11/05 01:57:39 INFO ShutdownHookManager: Shutdown hook called
[2023-11-05T01:57:39.313+0000] {spark_submit.py:491} INFO - 23/11/05 01:57:39 INFO ShutdownHookManager: Deleting directory /tmp/spark-9787a588-a14d-4d22-87df-7d6c0eaeefcb
[2023-11-05T01:57:39.367+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 156, in execute
    self._hook.submit(self._application)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 422, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark://dataeng-spark-master:7077 --name arrow-spark /spark-scripts/transform.py. Error code is: 1.
[2023-11-05T01:57:39.377+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=spark_airflow_dag, task_id=spark_submit_task, execution_date=20231105T015654, start_date=20231105T015709, end_date=20231105T015739
[2023-11-05T01:57:39.406+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 2 for task spark_submit_task (Cannot execute: spark-submit --master spark://dataeng-spark-master:7077 --name arrow-spark /spark-scripts/transform.py. Error code is: 1.; 293)
[2023-11-05T01:57:39.454+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-05T01:57:39.481+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
